import React from 'react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable'; // --- 1. CHANGE THIS IMPORT ---
import { FaDownload } from 'react-icons/fa';
import './ReportDisplay.css';

function ReportDisplay({ data }) {

  const handleDownloadPDF = () => {
    if (!data) return;

    // 1. Initialize Document and Define Colors/Fonts
    const doc = new jsPDF('p', 'mm', 'a4');
    const primaryColor = '#10b981'; // Your app's green
    const secondaryColor = '#f3f4f6'; // A light grey for backgrounds
    const fontColor = '#374151';
    const pageWidth = doc.internal.pageSize.getWidth();
    let currentY = 0;

    // --- Helper function to add a footer to each page ---
    const addFooter = () => {
      const pageCount = doc.internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        const footerText = `Page ${i} of ${pageCount} | Generated by ConsultAI`;
        doc.text(footerText, pageWidth / 2, 287, { align: 'center' });
        const disclaimer = "This analysis is for informational purposes only. Consult with a qualified healthcare professional.";
        doc.text(disclaimer, pageWidth / 2, 291, { align: 'center' });
      }
    };

    // 2. Draw the Header
    doc.setFillColor(primaryColor);
    doc.rect(0, 0, pageWidth, 25, 'F'); // Filled rectangle for header
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor('#FFFFFF');
    doc.text('ConsultAI Report Analysis', 14, 16);
    currentY = 35; // Set Y position below the header

    // 3. Add Patient Information
    doc.setFontSize(11);
    doc.setTextColor(fontColor);
    doc.setFont('helvetica', 'normal');
    doc.text(`Patient Name: ${data.patientInfo?.name || 'Not Found'}`, 14, currentY);
    doc.text(`Patient ID: ${data.patientInfo?.patientId || 'Not Found'}`, pageWidth - 14, currentY, { align: 'right' });
    currentY += 8;

    // 4. Add "Key Takeaways" in a styled box
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Key Takeaways', 14, currentY);
    currentY += 8;
    
    doc.setFillColor(secondaryColor);
    // Calculate box height dynamically based on content
    const takeawayLines = data.keyTakeaways.map(item => doc.splitTextToSize(`• ${item}`, 170));
    const boxHeight = takeawayLines.flat().length * 5 + 10;
    doc.rect(14, currentY - 2, 182, boxHeight, 'F'); // Background box

    doc.setFontSize(10);
    doc.setTextColor(fontColor);
    doc.setFont('helvetica', 'normal');
    takeawayLines.forEach(lines => {
        doc.text(lines, 20, currentY + 4);
        currentY += lines.length * 5;
    });
    currentY += 15; // Space after the box
    
    // 5. Generate the Advanced Test Results Table
    const tableHead = [['Test Name', 'Result', 'Interpretation']];
    const tableBody = data.testResults.map(test => [
      test.testName,
      `${test.result} ${test.units || ''}`,
      test.interpretation
    ]);

    autoTable(doc,{
      head: tableHead,
      body: tableBody,
      startY: currentY,
      theme: 'grid',
      styles: { fontSize: 9, cellPadding: 2.5, textColor: fontColor },
      headStyles: { 
        fillColor: primaryColor, 
        textColor: '#FFFFFF', 
        fontStyle: 'bold', 
        halign: 'center' 
      },
      alternateRowStyles: { fillColor: secondaryColor },
      // This hook allows us to style cells conditionally
      didDrawCell: (data) => {
        const isAbnormal = data.cell.raw?.toLowerCase() !== 'normal' && data.column.index === 2;
        if (isAbnormal) {
          doc.setTextColor('#e53e3e'); // Red color for abnormal interpretation text
          doc.setFont('helvetica', 'bold');
        }
      },
    });

    currentY = doc.lastAutoTable.finalY + 15;

    // 6. Add "Suggested Questions for Your Doctor"
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Suggested Questions for Your Doctor', 14, currentY);
    currentY += 8;

    doc.setFontSize(10);
    doc.setTextColor(fontColor);
    doc.setFont('helvetica', 'normal');
    data.questionsForDoctor.forEach(question => {
        const questionLines = doc.splitTextToSize(`• ${question}`, 170);
        doc.text(questionLines, 20, currentY);
        currentY += questionLines.length * 5 + 4;
    });

    // 7. Add Footer and Save
    addFooter();
    doc.save('ConsultAI_Report_Analysis.pdf');
  };

  if (!data || typeof data !== 'object') {
    return null;
  }
  
  // The JSX for displaying on the screen remains the same.
  const { keyTakeaways, patientInfo, testResults, recommendations, questionsForDoctor, summary } = data;

  return (
    <div className="report-container">
      {keyTakeaways && keyTakeaways.length > 0 && (
        <div className="takeaways-section">
          <h3>Key Takeaways</h3>
          <ul>
            {keyTakeaways.map((item, index) => <li key={index}>{item}</li>)}
          </ul>
        </div>
      )}

      <h4>Analysis Summary</h4>
      <p className="summary">{summary || 'No summary available.'}</p>

      {patientInfo && (
        <>
          <h4>Patient Information</h4>
          <div className="info-grid">
            <p><strong>Name:</strong> {patientInfo.name || "Not Found"}</p>
            <p><strong>ID:</strong> {patientInfo.patientId || "Not Found"}</p>
            <p><strong>DOB:</strong> {patientInfo.dob || "Not Found"}</p>
          </div>
        </>
      )}

      {testResults && testResults.length > 0 && (
        <>
          <h4>Test Results</h4>
          <table className="results-table">
            <thead>
              <tr>
                <th>Test Name</th>
                <th>Result</th>
                <th>Interpretation</th>
              </tr>
            </thead>
            <tbody>
              {testResults.map((test, index) => (
                <tr key={index} className={test.isCritical ? 'abnormal-row' : ''}>
                  <td>{test.testName}</td>
                  <td>{`${test.result} ${test.units || ''}`}</td>
                  <td>{test.interpretation}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </>
      )}

      {recommendations && recommendations.length > 0 && (
        <>
          <h4>Recommendations from Report</h4>
          <ul className="findings-list">
            {recommendations.map((rec, index) => <li key={index}>{rec}</li>)}
          </ul>
        </>
      )}

      {questionsForDoctor && questionsForDoctor.length > 0 && (
        <>
          <h4>Suggested Questions for Your Doctor</h4>
          <ul className="findings-list">
            {questionsForDoctor.map((question, index) => <li key={index}>{question}</li>)}
          </ul>
        </>
      )}
        
      <button onClick={handleDownloadPDF} className="download-pdf-btn">
        <FaDownload /> Download as PDF
      </button>
    </div>
  );
}

export default ReportDisplay;